version: "3.9"

services:

    #PHP Service
    php-apache-environment:
        container_name: iprint-php
        hostname: iprint.local
        build:
            context: .
            dockerfile: docker/dockerfile
        volumes:
            - .:/var/www/html/
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - iprint-db

    #Mariadb Database Service
    iprint-db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        networks:
            - app-network
        ports:
            - "3306:3306"
        volumes:
            - ./.docker-data/mariadb:/var/lib/mysql

#Docker Networks

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
networks:
    app-network:
        driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
